### ISSUE TITLE
plugin v2, magento v2.3.2, PHP 7.2.34 I don't see input for configuration

### ISSUE THREAD

**Issue by kostia-lev** [btcpayserver/magento2-plugin#1]
![image](https://user-images.githubusercontent.com/1144764/145674578-31a19daa-7569-4b0e-a055-ac48d44aecdb.png)

**Comment by woutersamaey** [comment]
Are you sure you installed the plugin v2 correctly (and not v1)?
And, are you viewing the config from the global scope?

I can't really think of a reason why this would not work.

Your PHP version is also outdated, so that may prove to be problematic in next steps.

**Comment by dni** [comment]
it also does not work for me, i do not even see the settings, i get an error the api_key base_url is missing, seems like a default value of the settings are missing

**Comment by dni** [comment]
oh, this issue gave me a hint though, i disabled single_store_mode now i get settings... :) great

**Comment by woutersamaey** [comment]
Can you tell me a bit more about this pls? I'm not aware of single store mode. Did you enable it manually or something?

**Comment by dni** [comment]
yes, there is a single-store mode, without stores / website scopes-
you can find it Settings > General > General > Single-Store Mode

**Comment by woutersamaey** [comment]
Okay, this was never tested. Can you make a PR so it gets added to the README pls?

**Comment by woutersamaey** [comment]
Thanks man. Can we close this issue now?

**Comment by dni** [comment]
i think the issuer above me was also in the wrong website scope, you do not see the apikey if you go to "Main Website" View

**Comment by woutersamaey** [comment]
Correct, most settings are in the global or store view scope. There's not much in website scope.

**Comment by woutersamaey** [comment]
@kostia-lev was your issue resolved?

**Comment by kostia-lev** [comment]
@woutersamaey it was installed incorrectly. It should be installed using composer only it cannot be copied

**Comment by woutersamaey** [comment]
This is the package you should install: https://packagist.org/packages/btcpayserver/magento2-btcpay-module

Is this what you used? If so, please give more detail as I am having trouble understanding your issue.
