### ISSUE TITLE
what is btcpay base url?

### ISSUE THREAD

**Issue by kostia-lev** [btcpayserver/magento2-plugin#10]
After installing plugin asks me for btcpay base url. Where I can get this?
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1144764/166945559-c4da295e-bd0d-49ad-95c1-4cd54147e879.png">

**Comment by woutersamaey** [comment]
It's literally where you installed your BTCPay Server. Should be something like https://www.mybtcpay.com
