### ISSUE TITLE
Due to multiple webhook call getting order place issue and server hanged

### ISSUE THREAD

**Issue by bhavintla** [btcpayserver/magento2-plugin#15]
Hi Team,

We are using your 
https://github.com/btcpayserver/magento2-plugin BTCPay payment extension with magneto 2 website.

We are facing challenges with webhooks when orders are being placed on our site.

Issues:
1. Multiple web hooks are getting created on every order automatically, creating an endless list of web hooks.

2. When the web hook count increases over a period of time, the load on the site increases, making it difficult for the site to load for others parallely.

Want to know why so many web hooks are getting created on every order? What could be possible causes and how do we resolve the issue?

Thanks

**Comment by woutersamaey** [comment]
Thanks for taking a look and addressing this @ndeet
