### ISSUE TITLE
order fails if you have only virtual products

### ISSUE THREAD

**Issue by dni** [btcpayserver/magento2-plugin#5]
if you have only downloadable or virtual products, magento diesnt require you to specify a shipping address. this break the ordering

i'm going to do a PR.

**Comment by woutersamaey** [comment]
Thanks. Should be easy enough I believe. Don't think we did much related to shipping. Prolly some optional metadata that we send to BTCPay, but that can be wrapped in an `if` or something like that.

**Comment by dni** [comment]
here is the PR https://github.com/btcpayserver/magento2-plugin/pull/6

now everything seems to work for me :) finally
