### ISSUE TITLE
installation manual is not correct

### ISSUE THREAD

**Issue by kostia-lev** [btcpayserver/magento2-plugin#8]
real package name is this:
https://packagist.org/packages/btcpayserver/magento2-btcpay-module
manual is not correct, please fix

**Comment by woutersamaey** [comment]
Where did you see this?

The readme has the correct package name
![image](https://user-images.githubusercontent.com/71019/146780506-975c2bef-9c28-42e0-8ca7-601fcc0e1dd6.png)

**Comment by kostia-lev** [comment]
![Uploading 9A6F4CDA-E9D0-4D97-80C1-BC09E6EE8FAA.png…]()

**Comment by kostia-lev** [comment]
![Uploading 812F713E-E8DD-496B-B89D-C49E3EFC9943.jpeg…]()

**Comment by kostia-lev** [comment]
Version two readme

**Comment by kostia-lev** [comment]
![0704B91D-7328-4C90-8754-922A666F7576](https://user-images.githubusercontent.com/1144764/146801142-aa83fa49-0a8a-4dc4-a618-139f538c2ab6.jpeg)

**Comment by woutersamaey** [comment]
Where are you seeing this? On master branch it is correct and that's the version you should use.

**Comment by kostia-lev** [comment]
v2 tag

**Comment by woutersamaey** [comment]
Please use the master branch

**Comment by woutersamaey** [comment]
@kostia-lev was your issue resolved?

**Comment by kostia-lev** [comment]
yes
