### ISSUE TITLE
btcpay server invoice id links incorrectly

### ISSUE THREAD

**Issue by qkimchi** [btcpayserver/magento2-plugin#9]
In magento admincp under "BTCPAY server invoices" clicking on a btcpay server invoice id links incorrectly because its missing a "/"  eg it tries to open "invoices/2pCgSdR1evVLMaE2vnpVCv" instead of "/invoices/2pCgSdR1evVLMaE2vnpVCv".

**Comment by woutersamaey** [comment]
@JudithWebdev can you take a look pls?

**Comment by JudithWebdev** [comment]
Hello @qkimchi, in the BTCPay module (v. 2.0.0) the link works fine. I can't reproduce this issue.

**Comment by JudithWebdev** [comment]
Dear @qkimchi, it depends on how you enter the BTC Pay Server URL, with a slash at the end or not. We have made an improvement so it doesn't matter how you enter the URL. We'll include this improvement in the next update. Thank you for reporting this issue!
